version: "3"

services:
  postgres:
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:3
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

volumes:
  postgres-data:
  redis-data:
  app:
